export const products = [
  {
    id: 1,
    name: 'Smart LED TV 43"',
    price: 38999,
    image: '/products/tvs.jpg',
    category: 'tvs',
    description: '43-inch Full HD Smart LED TV with vibrant colors.',
  },
  {
    id: 2,
    name: 'Samsung Galaxy A15',
    price: 21999,
    image: '/products/a15.jpg',
    category: 'phones',
    description: 'Affordable smartphone with long battery life.',
  },
  {
    id: 3,
    name: 'Blender Pro 600W',
    price: 7499,
    image: '/products/blender.jpg',
    category: 'kitchen',
    description: 'Powerful blender for smoothies and food prep.',
  },
  {
    id: 4,
    name: 'iPhone 15 Pro Max',
    price: 189999,
    image: '/products/phone.jpg',
    category: 'phones',
    description: '6.7-inch display, A17 chip, pro camera system.',
  },
  {
    id: 5,
    name: 'LG Washing Machine',
    price: 78500,
    image: '/products/washing machine.jpg',
    category: 'appliances',
    description: 'LG washing machine with 8kg capacity and auto-dry function.',
  },
  {
    id: 6,
    name: 'Electric Oven',
    price: 32999,
    image: '/products/electric oven.jpg',
    category: 'kitchen',
    description: 'Electric oven with multiple cooking functions.',
  },
  {
    id: 7,
    name: 'LG Double Door Fridge',
    price: 149999,
    image: '/products/fridge.jpg',
    category: 'appliances',
    description: 'LG double door fridge with 300L capacity.',
  },
];
