export const products = [
  {
    id: 1,
    name: 'Smart LED TV 43"',
    price: 38999,
    image: '/products/tvs.jpg',
    category: 'tvs',
    description: '43-inch Full HD Smart LED TV with vibrant colors.',
  },
  {
    id: 2,
    name: 'Samsung Galaxy A15',
    price: 21999,
    image: '/products/a15.jpg',
    category: 'smartphones',
    description: 'Affordable smartphone with long battery life.',
  },
  {
    id: 3,
    name: 'Blender Pro 600W',
    price: 7499,
    image: '/products/blender.jpg',
    category: 'kitchen-appliances',
    description: 'Powerful blender for smoothies and food prep.',
  },
  {
    id: 4,
    name: 'iPhone 15 Pro Max',
    price: 189999,
    image: '/products/phone.jpg',
    category: 'smartphones',
    description: '6.7-inch display, A17 chip, pro camera system.',
  },
  {
    id: 5,
    name: 'LG Washing Machine',
    price: 78500,
    image: '/products/washing machine.jpg',
    category: 'home-appliances',
    description: 'LG washing machine with 8kg capacity and auto-dry function.',
  },
  {
    id: 6,
    name: 'Electric Oven',
    price: 32999,
    image: '/products/electric oven.jpg',
    category: 'kitchen-appliances',
    description: 'Electric oven with multiple cooking functions.',
  },
  {
    id: 7,
    name: 'LG Double Door Fridge',
    price: 149999,
    image: '/products/fridge.jpg',
    category: 'home-appliances',
    description: 'LG double door fridge with 300L capacity.',
  },
  {
    id: 8,
    name: 'Tinana Pressure Cooker',
    price: 20999,
    image: '/products/prc.jpg',
    category: 'kitchen-appliances',
    description: 'Tinana pressure cooker with 6L capacity.',
  },
  {
    id: 9,
    name: 'Electric fan',
    price: 5999,
    image: '/products/electric-fan.jpg',
    category: 'home-appliances',
    description: 'Electric fan with 3-speed settings.',
  },
  {
    id: 10,
    name: 'cooker',
    price: 14999,
    image: '/products/cooker.jpg',
    category: 'kitchen-appliances',
    description: 'Electric/Gas cooker with an inbuilt oven.',
  },
  {
    id: 11,
    name: 'Samsung S23 Ultra',
    price: 99999,
    image: '/products/s24.jpg',
    category: 'smartphones',
    description: 'Samsung S24 Ultra with 12GB RAM and 512GB storage.',
  },
  {
    id: 12,
    name: 'Non Stick Pan Set',
    price: 4999,
    image: '/products/cooking pots.jpg',
    category: 'kitchen-appliances',
    description: 'Non-stick pan set with 5 pieces.',
  },
  { id: 13, 
    name: "iPhone 15 Pro Max", 
    category: "smartphones", 
    price: 119900, 
    image: "/products/iphone-15-pro-max.jpg", 
    description: "The latest iPhone with advanced features and improved performance." },
  { id: 14, 
    name: "Samsung Galaxy S24 Ultra", 
    category: "smartphones", 
    price: 129900, 
    image: "/products/samsung-galaxy-s24-ultra.jpg",
     description: "Flagship Samsung smartphone with advanced camera capabilities." },
  { id: 15, 
    name: "Google Pixel 8 Pro", 
    category: "smartphones", 
    price: 99900, 
    image: "/products/google-pixel-8-pro.jpg", 
    description: "Google's latest flagship smartphone with AI-powered features." },
  { id: 16, 
    name: "OnePlus 12", 
    category: "smartphones", 
    price: 79900, 
    image: "/products/oneplus-12.jpg", 
    description: "High-performance smartphone with fast charging and smooth performance." },
  { id: 17, 
    name: "Xiaomi 17 Pro Max", 
    category: "smartphones", 
    price: 79900, 
    image: "/products/xiaomi-17-pro-max.jpg", 
     
    description:"Premium Xiaomi smartphone with excellent camera and performance." },
  { id: 18, 
    name: "Tecno camon 40", 
    category: "smartphones", 
    price: 79900, 
    image: "/products/tecno-camon-40.jpg", 
    
    description:"Affordable smartphone with great battery life and performance."},
  { id: 19, 
    name: "Nothing Phone 2", 
    category: "smartphones", 
    price: 59900, 
    image: "/products/nothing-phone-2.jpg", 
     
    description: "Innovative smartphone with a unique design and performance." },
  { id: 20, 
    name: "Oppo Reno 15 Pro", 
    category: "smartphones", 
    price: 69900, 
    image: "/products/oppo-reno-15-pro.jpg", 
     
    description: "Premium smartphone with advanced camera and performance features." },

  //LAPTOPS
  { id: 21, 
    name: "MacBook Pro M3", 
    category: "laptops", 
    price: 199900, 
    image: "/products/macbook-pro-m3.jpg", 
     
    description: "The latest MacBook Pro with the powerful M3 chip and stunning display." },
  { id: 22, 
    name: "Dell XPS 15", 
    category: "laptops", 
    price: 179900, 
    image: "/products/dell-xps-15.jpg", 
     
    description: "Premium Dell laptop with a stunning display and powerful performance." },
  { id: 23, 
    name: "HP Spectre x360", 
    category: "laptops", 
    price: 149900, 
    image: "/products/hp-spectre-x360.jpg", 

    description: "Versatile HP laptop with a convertible design and excellent performance." },
  { id: 24, 
    name: "ASUS ROG Strix G16", 
    category: "laptops", 
    price: 189900, 
    image: "/products/asus-rog-strix-g16.jpg", 
     
    description:"High-performance gaming laptop with advanced cooling and graphics capabilities." },
  { id: 25, 
    name: "Microsoft Surface Laptop 5", 
    category: "laptops", 
    price: 129900, 
    image: "/products/surface-laptop-5.jpg",
   description:"Elegant Microsoft laptop with a stunning touchscreen display and powerful performance." },
  { id: 26, 
    name: "Lenovo ThinkPad X1 Carbon", 
    category:"laptops" , 
    price :159900 , 
    image:"/products/lenovo-thinkpad-x1-carbon.jpg" ,  
    description :"Lightweight and powerful Lenovo laptop perfect for professionals." },
  { id: 27, 
    name: "Acer Predator Helios 16", 
    category: "laptops", 
    price: 169900, 
    image: "/products/acer-predator-helios-16.jpg", 
    description: "High-performance gaming laptop with advanced cooling and graphics capabilities." },
  { id: 28, 
    name: "Razer Blade 16", 
    category: "laptops", 
    price: 279900, 
    image: "/products/razer-blade-16.jpg", 
     
    description: "Premium gaming laptop with advanced features and performance." },

  //HOME APPLIANCES
  { id: 29, 
    name: "Dyson V15 Vacuum", 
    category: "home-appliances", 
    price: 7490, 
    image: "/products/dyson-v15-vacuum.jpg", 
    
    description: "Powerful cordless vacuum cleaner with advanced filtration." },
  { id: 30, 
    name: "LG OLED TV 65\"", 
    category: "home-appliances", 
    price: 249900, 
    image: "/products/lg-oled-tv-65.jpg", 
     
    description: "Premium LG OLED TV with stunning picture quality and smart features." },
  { id: 31, 
    name: "Samsung Smart Refrigerator", 
    category: "home-appliances", 
    price: 219900, 
    image: "/products/samsung-smart-refrigerator.jpg", 
     
    description: "Smart Samsung refrigerator with advanced cooling and storage features." },
  { id: 32, 
    name: "Samsung QLED TV 75\"", 
    category: "home-appliances", 
    price: 299900, 
    image: "/products/samsung-qled-tv-75.jpg", 
     
    description:"Premium Samsung QLED TV with vibrant colors and smart capabilities." },
  { id: 33, 
    name: "Whirlpool Washing Machine", 
    category: "home-appliances", 
    price: 89900, 
    image: "/products/whirlpool-washing-machine.jpg", 
     
    description:"Reliable Whirlpool washing machine with advanced cleaning technology." },
  { id: 34, 
    name: "Samsung Odyssey G9 Monitor", 
    category: "home-appliances", 
    price: 149900, 
    image: "/products/samsung-odyssey-g9.jpg", 
    
    description:"High-performance Samsung monitor with immersive gaming experience." },
  { id: 35, 
    name: "Sonos Arc Soundbar", 
    category: "home-appliances", 
    price: 89900, 
    image: "/products/sonos-arc-soundbar.jpg", 
     
    description: "Premium Sonos soundbar with immersive audio experience." },
  //KITCHEN APPLIANCES
  { id: 36, 
    name: "KitchenAid Stand Mixer", 
    category: "kitchen-appliances", 
    price: 42900, 
    image: "/products/kitchenaid-stand-mixer.jpg", 
     
    description:"High-quality KitchenAid stand mixer for all your baking needs." },
  { id: 37, 
    name: "Ninja Air Fryer", 
    category: "kitchen-appliances", 
    price: 12900, 
    image: "/products/ninja-air-fryer.jpg", 
     
    description:"Versatile Ninja air fryer for healthy and crispy cooking." },
  { id: 38, 
    name: "Breville Espresso Machine", 
    category: "kitchen-appliances", 
    price: 69900, 
    image: "/products/breville-espresso-machine.jpg", 
     description:"Professional-grade Breville espresso machine for perfect coffee." },
  { id: 39, 
    name: "Vitamix Blender", 
    category: "kitchen-appliances",
    price: 54900, 
    image: "/products/vitamix-blender.jpg", 
     
    description:"High-performance Vitamix blender for smoothies and more." },
  { id: 40, 
    name: "Instant Pot Duo", 
    category: "kitchen-appliances", 
    price: 9900, 
    image: "/products/instant-pot-duo.jpg", 
     
    description:"Versatile Instant Pot Duo for quick and easy cooking." },
  { id: 41, 
    name: "Toshiba Microwave", 
    category: "kitchen-appliances", 
    price: 14900, 
    image: "/products/toshiba-microwave.jpg", 
     
    description:"Reliable Toshiba microwave with easy-to-use controls." },
  { id: 42, 
    name: "Cuisinart Food Processor", 
    category: "kitchen-appliances", 
    price: 19900, 
    image: "/products/cuisinart-food-processor.jpg", 
     
    description:"Efficient Cuisinart food processor for all your prep needs." }
];
